apiVersion: v1
kind: Namespace
metadata:
  name: thesis-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-test-deployment
  namespace: thesis-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thesis-app
  template:
    metadata:
      labels:
        app: thesis-app
      annotations:
        bandwidth: "10mbps"
        loss: "2%"
    spec:
      containers:
        - name: go-test-container
          image: beranabus/go-test-service:latest
          ports:
          - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: go-test-service
  namespace: thesis-ns
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: thesis-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-test-ingress
  namespace: thesis-ns
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-test-service
            port:
              number: 80
